-- CURSO - ORACLE DATABASE: MANIPULANDO DADOS COM DML

-- CRIANDO TABELAS
CREATE TABLE PRODUTOS(
    CODIGO VARCHAR(10) NOT NULL,
    DESCRITOR VARCHAR(100) NULL,
    SABOR VARCHAR(50) NULL,
    TAMANHO VARCHAR(50) NULL,
    EMBALAGEM VARCHAR(50) NULL,
    PRECO_LISTA FLOAT NULL,
    PRIMARY KEY (CODIGO)
);

CREATE TABLE VENDEDORES(
    MATRICULA VARCHAR(5) NOT NULL,
    NOME VARCHAR(100) NULL,
    BAIRRO VARCHAR(50) NULL,
    COMISSAO FLOAT NULL,
    DATA_ADMISSAOAO DATE NULL,
    FERIAS INTEGER NULL,
    PRIMARY KEY (MATRICULA)
);

