-- CURSO - ORACLE DATABASE: MANIPULANDO DADOS COM DML

-- CRIANDO TABELAS - COMANDOS DDL - DATA MANIPULATION LANGUAGE
CREATE TABLE PRODUTOS(
    CODIGO VARCHAR(10) NOT NULL,
    DESCRITOR VARCHAR(100) NULL,
    SABOR VARCHAR(50) NULL,
    TAMANHO VARCHAR(50) NULL,
    EMBALAGEM VARCHAR(50) NULL,
    PRECO_LISTA FLOAT NULL,
    PRIMARY KEY (CODIGO)
);

CREATE TABLE VENDEDORES(
    MATRICULA VARCHAR(5) NOT NULL,
    NOME VARCHAR(100) NULL,
    BAIRRO VARCHAR(50) NULL,
    COMISSAO FLOAT NULL,
    DATA_ADMISSAOAO DATE NULL,
    FERIAS INTEGER NULL,
    PRIMARY KEY (MATRICULA)
);

ALTER TABLE VENDEDORES
RENAME COLUMN DATA_ADMISSAOAO TO DATA_ADMISSAO;

CREATE TABLE CLIENTES(
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(100) NULL,
    ENDERECO VARCHAR(150) NULL,
    BAIRRO VARCHAR(50) NULL,
    CIDADE VARCHAR(50) NULL,
    ESTADO VARCHAR(50) NULL,
    CEP VARCHAR(8) NULL,
    DATA_NASC DATE NULL,
    IDADE INTEGER NULL,
    GENERO VARCHAR(1) NULL,
    LIMITE_CREDITO FLOAT NULL,
    VOLUME_COMPRA FLOAT NULL,
    PRIMEIRA_COMPRA INTEGER,
    CONSTRAINT CLIENTES_PK PRIMARY KEY (CPF)
    );


CREATE TABLE TABELA_DE_VENDAS(
    NUMERO VARCHAR(5) NOT NULL,
    DATA_VENDA DATE NULL,
    CPF VARCHAR(11) NOT NULL,
    MATRICULA VARCHAR(5) NOT NULL,
    IMPOSTO FLOAT NULL,
    CONSTRAINT VENDAS_PK PRIMARY KEY (NUMERO)   
);

ALTER TABLE TABELA_DE_VENDAS
ADD CONSTRAINT FK_CLIENTES FOREIGN KEY (CPF)
REFERENCES CLIENTES (CPF);

