-- DATABASE https://en.wikibooks.org/wiki/SQL_Exercises/The_computer_store
-- Oracle SQL Developes version 20.2.0
-- CRIANDO TABELAS - COMANDOS DDL - DATA MANIPULATION LANGUAGE
CREATE TABLE MANUFACTURERS(
    MCODE INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    CONSTRAINT MANUFACTURERS_PK PRIMARY KEY (MCODE)
);

CREATE TABLE PRODUCTS(
    PCODE INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRICE FLOAT NOT NULL,
    MANUFACTURER INTEGER NOT NULL,
    CONSTRAINT PRODUCTS_PK PRIMARY KEY (PCODE),
    CONSTRAINT FK_MANUFACTURERS_CODE REFERENCES MANUFACTURERS(MCODE)
);


-- SAMPLE DATASET
INSERT INTO MANUFACTURERS(MCODE,NAME) VALUES (1,'Sony'),(2,'Creative Labs'),(3,'Hewlett-Packard'),(4,'Iomega'),(5,'Fujitsu'),(6,'Winchester');
INSERT INTO PRODUCTS(PCODE,NAME,PRICE,MANUFACTURER) VALUES(1,'Hard drive',240,5),(2,'Memory',120,6),(3,'ZIP drive',150,4),(4,'Floppy disk',5,6),(5,'Monitor',240,1),
(6,'DVD drive',180,2),(7,'CD drive',90,2),(8,'Printer',270,3),(9,'Toner cartridge',66,3),(10,'DVD burner',180,2);