-- Questions SQL
-- 1. Select the names of all the products in the store. 
-- 2. Select the names and the prices of all the products in the store.
-- 3. Select the name of the products with a price less than or equal to $200. 
